/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import config.Koneksi;
import controller.LoginController;
import controller.PenjualanController;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.App;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user_
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    public PelangganView pelangganView;
    public JenisView jenisView;
    public UkuranView ukuranView;
    public PakaianView pakaianView;
    public DetailPakaianView detailPakaianView;
    public PenjualanView penjualanView;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemJenis = new javax.swing.JMenuItem();
        itemUkuran = new javax.swing.JMenuItem();
        itemMasterPakaian = new javax.swing.JMenuItem();
        itemPelanggan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemDetailPakaian = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemPenjualan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        tombolRiwayatPenjualan = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        tombolLaporanBarang = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        tombolLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Batik Nadril");

        javax.swing.GroupLayout menuDesktopLayout = new javax.swing.GroupLayout(menuDesktop);
        menuDesktop.setLayout(menuDesktopLayout);
        menuDesktopLayout.setHorizontalGroup(
            menuDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        menuDesktopLayout.setVerticalGroup(
            menuDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setMargin(new java.awt.Insets(0, 10, 0, 0));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(289, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Toko.png"))); // NOI18N
        jMenu1.setText("Master");

        itemJenis.setText("Master Jenis");
        itemJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemJenisActionPerformed(evt);
            }
        });
        jMenu1.add(itemJenis);

        itemUkuran.setText("Master Ukuran");
        itemUkuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUkuranActionPerformed(evt);
            }
        });
        jMenu1.add(itemUkuran);

        itemMasterPakaian.setText("Master Pakaian");
        itemMasterPakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMasterPakaianActionPerformed(evt);
            }
        });
        jMenu1.add(itemMasterPakaian);

        itemPelanggan.setText("Master Pelanggan");
        itemPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPelangganActionPerformed(evt);
            }
        });
        jMenu1.add(itemPelanggan);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Box Add.png"))); // NOI18N
        jMenu4.setText("Detail");

        itemDetailPakaian.setText("Detail Pakaian");
        itemDetailPakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDetailPakaianActionPerformed(evt);
            }
        });
        jMenu4.add(itemDetailPakaian);

        jMenuBar1.add(jMenu4);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Data Penjualan.png"))); // NOI18N
        jMenu2.setText("Transaksi");

        itemPenjualan.setText("Penjualan");
        itemPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPenjualanActionPerformed(evt);
            }
        });
        jMenu2.add(itemPenjualan);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Notes.png"))); // NOI18N
        jMenu3.setText("Laporan");

        jMenu6.setText("Penjualan");

        tombolRiwayatPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/document-print.png"))); // NOI18N
        tombolRiwayatPenjualan.setText("Riwayat Penjualan");
        tombolRiwayatPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolRiwayatPenjualanActionPerformed(evt);
            }
        });
        jMenu6.add(tombolRiwayatPenjualan);

        jMenu3.add(jMenu6);

        jMenu7.setText("Gudang");

        tombolLaporanBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/document-print.png"))); // NOI18N
        tombolLaporanBarang.setText("Barang");
        tombolLaporanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLaporanBarangActionPerformed(evt);
            }
        });
        jMenu7.add(tombolLaporanBarang);

        jMenu3.add(jMenu7);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-settings-48.png"))); // NOI18N
        jMenu5.setText("Pengaturan");

        tombolLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        tombolLogout.setText("Logout");
        tombolLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLogoutActionPerformed(evt);
            }
        });
        jMenu5.add(tombolLogout);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPelangganActionPerformed
        if (pelangganView == null) {
            pelangganView = new PelangganView();
            menuDesktop.add(pelangganView);
            pelangganView.setVisible(true);
        } else {
            pelangganView.toFront();
        }
    }//GEN-LAST:event_itemPelangganActionPerformed

    private void itemPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPenjualanActionPerformed
         if (penjualanView == null) {
            penjualanView = new PenjualanView();
            menuDesktop.add(penjualanView);
            penjualanView.setVisible(true);
        } else {
            penjualanView.toFront();
        }
    }//GEN-LAST:event_itemPenjualanActionPerformed

    private void itemJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemJenisActionPerformed
        if (jenisView == null) {
            jenisView = new JenisView();
            menuDesktop.add(jenisView);
            jenisView.setVisible(true);
        } else {
            jenisView.toFront();
        }
    }//GEN-LAST:event_itemJenisActionPerformed

    private void itemUkuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUkuranActionPerformed
        if (ukuranView == null) {
            ukuranView = new UkuranView();
            menuDesktop.add(ukuranView);
            ukuranView.setVisible(true);
        } else {
            ukuranView.toFront();
        }
    }//GEN-LAST:event_itemUkuranActionPerformed

    private void itemMasterPakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMasterPakaianActionPerformed
        if (pakaianView == null) {
            pakaianView = new PakaianView();
            menuDesktop.add(pakaianView);
            pakaianView.setVisible(true);
        } else {
            pakaianView.toFront();
        }
    }//GEN-LAST:event_itemMasterPakaianActionPerformed

    private void itemDetailPakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDetailPakaianActionPerformed
         if (detailPakaianView == null) {
            detailPakaianView = new DetailPakaianView();
            menuDesktop.add(detailPakaianView);
            detailPakaianView.setVisible(true);
        } else {
            detailPakaianView.toFront();
        }
    }//GEN-LAST:event_itemDetailPakaianActionPerformed

    private void tombolRiwayatPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolRiwayatPenjualanActionPerformed
        try {
            Koneksi koneksi = new Koneksi();
            HashMap param = new HashMap();
            String rootPath = new File(".").getCanonicalPath();
            String path = "src/laporan/penjualan.jasper";
            JasperPrint jp = JasperFillManager.fillReport(rootPath+"/"+path, param, koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(PenjualanController.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombolRiwayatPenjualanActionPerformed

    private void tombolLaporanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLaporanBarangActionPerformed
        try {
            Koneksi koneksi = new Koneksi();
            HashMap param = new HashMap();
            String rootPath = new File(".").getCanonicalPath();
            String path = "src/laporan/gudang.jasper";
            JasperPrint jp = JasperFillManager.fillReport(rootPath+"/"+path, param, koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(PenjualanController.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombolLaporanBarangActionPerformed

    private void tombolLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLogoutActionPerformed
        App.menuView.setVisible(false);
        LoginController.id_admin = null;
        LoginView loginView = new LoginView();
        loginView.setVisible(true);
    }//GEN-LAST:event_tombolLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemDetailPakaian;
    private javax.swing.JMenuItem itemJenis;
    private javax.swing.JMenuItem itemMasterPakaian;
    private javax.swing.JMenuItem itemPelanggan;
    private javax.swing.JMenuItem itemPenjualan;
    private javax.swing.JMenuItem itemUkuran;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane menuDesktop;
    private javax.swing.JMenuItem tombolLaporanBarang;
    private javax.swing.JMenuItem tombolLogout;
    private javax.swing.JMenuItem tombolRiwayatPenjualan;
    // End of variables declaration//GEN-END:variables
}
